services:
  postgres_tutorial:
    image: postgres:14.4  # version matches with gcp cloud sql
    container_name: postgres_tutorial
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always
    user: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'postgres_tutorial_data:/var/lib/postgresql/data'

volumes:
  postgres_tutorial_data: