// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (*Employee, error)
	DeleteEmployee(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetAllEmployee(ctx context.Context) ([]*Employee, error)
	GetEmployeeById(ctx context.Context, id uuid.UUID) (*Employee, error)
	//     name = coalesce(sqlc.narg('name'), name),
	//     dob = coalesce(sqlc.narg('dob'), dob),
	//     department = coalesce(sqlc.narg('department'), department),
	//     job_title = coalesce(sqlc.narg('job_title'), job_title),
	//     address = coalesce(sqlc.narg('address'), address),
	//     joined_at = coalesce(sqlc.narg('joined_at'), joined_at)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (*Employee, error)
}

var _ Querier = (*Queries)(nil)
